apiVersion: v1
kind: Service
metadata:
  name: junos-acl-analyzer
  labels:
    app.kubernetes.io/name: junos-acl-analyzer
spec:
  selector:
    app.kubernetes.io/name: junos-acl-analyzer
  ports:
    - name: http
      port: 80
      targetPort: http
